fixtures:
  #repositories:
    #stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    #apt: git://github.com/puppetlabs/puppetlabs-apt.git
  symlinks:
    owncloud: "#{source_dir}"
    # You may need to add more modules in here
    #authbind: "#{source_dir}/../authbind"
    #apt: "#{source_dir}/../apt"
