language: ruby
rvm:
  - 1.9.3
#script: "rake spec"
#task: default => [:spec, :lint]
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.7.23
notifications:
  email: false
#gemfile: .gemfile
